### ISSUE TITLE
Pretty printing Python AST

### ISSUE THREAD

**Issue by SunghoLee** [grievejia/pyre-ast#1]
Hello all, 

I found this awesome project, and this project would be very helpful for me to conduct my research. 
But I have not found a pretty printing feature for the concrete AST. Does pyre-ast support the pretty printing? And if it does, how can I use it?

Thanks for the great project!

**Comment by grievejia** [comment]
Thanks for your interest and kind words!

> Does pyre-ast support the pretty printing?

No it doesn't. If you want to dump the ast for debugging purpose, you can convert the concrete AST nodes into sexps and print them. If you do want prettified, nicely-formatted printer, you'd need to implement that as a downstream pass yourself. At least for now.

**Comment by SunghoLee** [comment]
Thanks for the response. Okay, the response is pretty helpful.
