### ISSUE TITLE
Typo in concrete AST

### ISSUE THREAD

**Issue by Isaac-Lee** [grievejia/pyre-ast#3]
Hello!

I am a student making a python interpreter using this project as a frontend.
When I was reading a concrete AST, I realized there are some typo error in the code below. (In my opinion)

https://github.com/grievejia/pyre-ast/blob/ae943492e22ec101a795e89cf97e78b9ba50a91e/lib/concrete.ml#L340-L359

There are some parts written in `Pattern.t list` instead of `t list` inside of Pattern module.
I think it's a typo, but I'd like to know if you have any special intentions written like this.

Thanks!

**Comment by grievejia** [comment]
Thanks for pointing it out! 

No there's no specific reason why they have to be `Pattern.t`. Either `t` or `Pattern.t` works, but I think we should avoid using both for the sake of consistency.
